[options]
db_host = localhost
db_password = oca
# using runner user because of this pytest-odoo
# issue https://github.com/camptocamp/pytest-odoo/issues/81
db_user = runner
db_port = 5432

module_change_auto_install =
    base_install_request,
    google_gmail,
    iap,
    mail_bot,
    partner_autocomplete,
    sms